recipes-kernel: nvidia-kernel-oot: remove DTB file name
bitbake virtual/dtb failed due to do_package_qa error. Remove
dtsfilename in DTB file to fix it.

error log:
  ERROR: nvidia-kernel-oot-dtb-39.2.0-r0 do_package_qa: QA Issue:
  File tegra234-tek-orin+p3767-0000-nv.dtb in package
  nvidia-kernel-oot-dtb contains reference to TMPDIR [buildpaths]